const categorias = [
  {
    text: "Desarrollo Web",
    subcategorias: [
      {
        text: "Frontend",
        subsubcategorias: [
          { text: "HTML" },
          { text: "CSS" },
          { text: "JavaScript" },
          { text: "React" },
          { text: "Vue.js" },
        ],
      },
      {
        text: "Backend",
        subsubcategorias: [
          { text: "Node.js" },
          { text: "Express.js" },
          { text: "Django" },
          { text: "Ruby on Rails" },
          { text: "PHP" },
        ],
      },
      { text: "Diseño Web" },
      { text: "E-commerce" },
      { text: "SEO" },
      { text: "Responsive Design" },
      { text: "Web Accessibility" },
    ],
  },
  {
    text: "Tecnologías de la Información",
    subcategorias: [
      { text: "Redes" },
      { text: "Seguridad Informática" },
      {
        text: "Bases de Datos",
        subsubcategorias: [
          { text: "MySQL" },
          { text: "MongoDB" },
          { text: "PostgreSQL" },
          { text: "SQL Server" },
          { text: "Oracle" },
        ],
      },
      { text: "Cloud Computing" },
      { text: "Sistemas Operativos" },
      { text: "Ciberseguridad" },
      { text: "Virtualización" },
      { text: "Gestión de Proyectos TI" },
    ],
  },
  {
    text: "Programación",
    subcategorias: [
      { text: "JavaScript" },
      { text: "Python" },
      { text: "Java" },
      { text: "C++" },
      { text: "Ruby" },
      { text: "Swift" },
      { text: "PHP" },
      { text: "Go" },
    ],
  },
  {
    text: "Diseño Gráfico",
    subcategorias: [
      { text: "Adobe Illustrator" },
      { text: "Adobe Photoshop" },
      { text: "Adobe InDesign" },
      { text: "Diseño de Logotipos" },
      { text: "Diseño de Flyers" },
      { text: "Diseño de UI/UX" },
      { text: "Diseño de Carteles" },
      { text: "Diseño de Animaciones" },
    ],
  },
  {
    text: "Marketing Digital",
    subcategorias: [
      { text: "SEO" },
      { text: "Marketing de Contenidos" },
      { text: "Publicidad en Redes Sociales" },
      { text: "Email Marketing" },
      { text: "Marketing de Influencers" },
      { text: "Analítica Web" },
      { text: "Estrategia de Marketing" },
      { text: "Marketing Automation" },
    ],
  },
  {
    text: "Idiomas",
    subcategorias: [
      { text: "Inglés" },
      { text: "Español" },
      { text: "Francés" },
      { text: "Alemán" },
      { text: "Chino Mandarín" },
      { text: "Italiano" },
      { text: "Japonés" },
      { text: "Ruso" },
    ],
  },
  {
    text: "Arte y Creatividad",
    subcategorias: [
      { text: "Pintura" },
      { text: "Escultura" },
      { text: "Fotografía" },
      { text: "Dibujo" },
      { text: "Arte Digital" },
      { text: "Música" },
      { text: "Escritura Creativa" },
      { text: "Teatro y Actuación" },
    ],
  },
  {
    text: "Negocios y Emprendimiento",
    subcategorias: [
      { text: "Gestión Empresarial" },
      { text: "Planificación Estratégica" },
      { text: "Marketing Empresarial" },
      { text: "Finanzas Corporativas" },
      { text: "Emprendimiento Digital" },
      { text: "Gestión de Proyectos" },
      { text: "Liderazgo" },
      { text: "Ventas y Negociación" },
    ],
  },
  {
    text: "Ciencia y Tecnología",
    subcategorias: [
      { text: "Astronomía" },
      { text: "Biología" },
      { text: "Química" },
      { text: "Física" },
      { text: "Robótica" },
      { text: "Inteligencia Artificial" },
      { text: "Ciencia de Datos" },
      { text: "Nanotecnología" },
    ],
  },
  {
    text: "Salud y Bienestar",
    subcategorias: [
      { text: "Nutrición" },
      { text: "Ejercicio Físico" },
      { text: "Meditación y Mindfulness" },
      { text: "Psicología" },
      { text: "Yoga" },
      { text: "Terapias Alternativas" },
      { text: "Cuidado de la Salud Mental" },
      { text: "Primeros Auxilios" },
    ],
  },
  {
    text: "Cocina y Gastronomía",
    subcategorias: [
      { text: "Cocina Internacional" },
      { text: "Repostería" },
      { text: "Cocina Saludable" },
      { text: "Maridaje de Vinos" },
      { text: "Cocina Étnica" },
      { text: "Chef Profesional" },
      { text: "Cocina Vegetariana" },
      { text: "Cocina de Autor" },
    ],
  },
  {
    text: "Arquitectura y Diseño de Interiores",
    subcategorias: [
      { text: "Diseño de Edificios" },
      { text: "Diseño de Interiores Residenciales" },
      { text: "Diseño de Espacios Comerciales" },
      { text: "Diseño Sostenible" },
      { text: "Paisajismo" },
      { text: "Diseño de Mobiliario" },
      { text: "Arquitectura Moderna" },
      { text: "Restauración de Edificios Históricos" },
    ],
  },
  // Otras categorías, subcategorías y subsubcategorías pueden seguir aquí
];

export default categorias;
