"use client";
import type { Metadata } from "next";

import "../shared/styles/carbon.scss";

import Footer from "@/shared/components/Footer/Footer";
import MenuPhone from "@/shared/components/MenuPhone/MenuPhone";
import Navbar from "@/shared/components/Navbar/Navbar";
import "react-minimal-side-navigation/lib/ReactMinimalSideNavigation.css";
import "./globals.css";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Clean Architecture",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <Providers>
        <body className="relative">
          <Navbar />
          <MenuPhone />

          <section>{children}</section>

          <Footer />
        </body>
      </Providers>
    </html>
  );
}
